INSERT INTO user VALUES (  1, '장유정', 1,  0, 'Oh My 4년' );
INSERT INTO user VALUES (  2, '김진곤', 2,  1, 'Oh My 4년' );
INSERT INTO user VALUES (  3, '장시영', 2,  1, 'Oh My 4년' );
INSERT INTO user VALUES (  4, '봉주영', 2,  1, 'Oh My 4년' );
INSERT INTO user VALUES (  5, '김세진', 2,  1, 'Oh My 4년' );
INSERT INTO user VALUES (  6, '윤종민', 2,  1, 'Oh My 4년' );
INSERT INTO user VALUES (  7, '안규태', 2,  1, 'Oh My 4년' );
INSERT INTO user VALUES (  8, '안창현', 1,  0, '퇴근한다고 전해라' );
INSERT INTO user VALUES (  9, '김연주', 2,  8, '퇴근한다고 전해라' );
INSERT INTO user VALUES ( 10, '김용현', 2,  8, '퇴근한다고 전해라' );
INSERT INTO user VALUES ( 11, '최지원', 2,  8, '퇴근한다고 전해라' );
INSERT INTO user VALUES ( 12, '우영주', 2,  8, '퇴근한다고 전해라' );
INSERT INTO user VALUES ( 13, '정수민', 2,  8, '퇴근한다고 전해라' );
INSERT INTO user VALUES ( 14, '노상범', 1,  0, 'Re-Member' );
INSERT INTO user VALUES ( 15, '구하나', 2, 14, 'Re-Member' );
INSERT INTO user VALUES ( 16, '정진아', 2, 14, 'Re-Member' );
INSERT INTO user VALUES ( 17, '박은환', 2, 14, 'Re-Member' );
INSERT INTO user VALUES ( 18, '박수영', 2, 14, 'Re-Member' );
INSERT INTO user VALUES ( 19, '최병훈', 2, 14, 'Re-Member' );
INSERT INTO user VALUES ( 20, '우정범', 1,  0, '헤븐조선' );
INSERT INTO user VALUES ( 21, '박송원', 2, 20, '헤븐조선' );
INSERT INTO user VALUES ( 22, '정한별', 2, 20, '헤븐조선' );
INSERT INTO user VALUES ( 23, '이홍주', 2, 20, '헤븐조선' );
INSERT INTO user VALUES ( 24, '이희원', 1,  0, '균형 직접 민주주의' );
INSERT INTO user VALUES ( 25, '이용재', 2, 24, '균형 직접 민주주의' );
INSERT INTO user VALUES ( 26, '임익재', 2, 24, '균형 직접 민주주의' );
INSERT INTO user VALUES ( 27, '황원근', 2, 24, '균형 직접 민주주의' );
INSERT INTO user VALUES ( 28, '오상택', 1,  0, 'On시위OFF' );
INSERT INTO user VALUES ( 29, '임춘봉', 2, 28, 'On시위OFF' );
INSERT INTO user VALUES ( 30, '안영희', 2, 28, 'On시위OFF' );
INSERT INTO user VALUES ( 31, '김도영', 2, 28, 'On시위OFF' );
