insert into user values ( 1, '장유정', 1, 0, 'Oh My 4년' );
insert into user values ( 2, '김진곤', 2, 0, 'Oh My 4년' );
insert into user values ( 3, '장시영', 2, 0, 'Oh My 4년' );
insert into user values ( 4, '봉주영', 2, 0, 'Oh My 4년' );
insert into user values ( 5, '김세진', 2, 0, 'Oh My 4년' );
insert into user values ( 6, '윤종민', 2, 0, 'Oh My 4년' );
insert into user values ( 7, '안규태', 2, 0, 'Oh My 4년' );
insert into user values ( 8, '안창현', 1, 0, '퇴근한다고 전해라' );
insert into user values ( 9, '김연주', 2, 0, '퇴근한다고 전해라' );
insert into user values ( 11, '김용현', 2, 0, '퇴근한다고 전해라' );
insert into user values ( 12, '최지원', 2, 0, '퇴근한다고 전해라' );
insert into user values ( 13, '우영주', 2, 0, '퇴근한다고 전해라' );
insert into user values ( 14, '정수민', 2, 0, '퇴근한다고 전해라' );
insert into user values ( 15, '노상범', 1, 0, 'Re-Member' );
insert into user values ( 16, '구하나', 2, 0, 'Re-Member' );
insert into user values ( 17, '정진아', 2, 0, 'Re-Member' );
insert into user values ( 18, '박은환', 2, 0, 'Re-Member' );
insert into user values ( 19, '박수영', 2, 0, 'Re-Member' );
insert into user values ( 20, '최병훈', 2, 0, 'Re-Member' );
insert into user values ( 21, '우정범', 1, 0, '헤븐조선' );
insert into user values ( 22  '박송원', 2, 0, '헤븐조선' );
insert into user values ( 23, '정한별', 2, 0, '헤븐조선' );
insert into user values ( 24, '이홍주', 2, 0, '헤븐조선' );
insert into user values ( 25, '이희원', 1, 0, '균형 직접 민주주의' );
insert into user values ( 26, '이용재', 2, 0, '균형 직접 민주주의' );
insert into user values ( 27, '임익재', 2, 0, '균형 직접 민주주의' );
insert into user values ( 28, '황원근', 2, 0, '균형 직접 민주주의' );
insert into user values ( 29, '오상택', 1, 0, 'On시위OFF' );
insert into user values ( 30, '임춘봉', 2, 0, 'On시위OFF' );
insert into user values ( 31, '안영희', 2, 0, 'On시위OFF' );
insert into user values ( 32, '김도영', 2, 0, 'On시위OFF' );
